### ISSUE TITLE
[Bug] Can hear other players' hit sounds

### ISSUE THREAD

**Issue by throwitaway99** [ZehsTeam/Lethal-Company-Hitmarker#1]
I haven't tested this very thoroughly, and it's possible I was also able to see(?) the effects (not to mention that I was running many other mods), but it's been a while and it was in one occasion so I can't say for certain. However, what I 100% *do* recall was that I was able to hear the hit effect when another player was shooting an enemy (mimics in this case), and I was able to hear it from the other side of the map. I'm going to assume that this isn't intentional behavior, and rather that you are only supposed to hear/see *your own* hit effects - which would certainly be preferred.

**Comment by ZehsTeam** [comment]
I have noticed something like this when a nutcracker would shoot another enemy or other. This should hopefully be fixed in the new update I just pushed. v1.1.0

Thanks for making a bug report <3
Please let me know if you find any other issues.
